### ISSUE TITLE
Wrong implementation of dawa-autocomplete2

### ISSUE THREAD

**Issue by rasmus0201** [AncaIO/vue-dawa#13]
Hi. I stumbled across your really nice DAWA integration for Vue, though I have encountered som bugs, which should be easily fixed.

1)  When you selected from the suggestion list the suggestions doesn't update, because it doesn't set the `skipVejnavn` variable to true, which later sets the `startfra = 'adgangsadresse'`. This is sometimes required to get further suggestions.

This bug can be fixed by just calling the `select` method on the `DawaService` class from the vue component:

VueDawa.vue - Line 270 (select method):
```js
if ((this.terms.length >= this.defaultCaretPos && this.caretPos !== this.terms.length) || (item.type !== this.dawaService.options.type) || this.results.length > 1) {
    // this.dawaService.update(this.terms, this.caretPos)
    this.dawaService.select(item);
}
```

2) The `tekst` property is sometimes ill-formed from the DAWA api - including empty commas (eg. "Slåenvej 1, , 3120 Dronningmølle")

The dawa-autocomplete2 fixes this by manually parse the tekst. It should be fixed with the following code:

VueDawa.vue - Line 222 (handleResults method):
```js
for (let item of response) {
    let rows = item.forslagstekst.split('\n').map(row => row.replace(/ /g, '\u00a0'))
    item.suggestion = rows.join(', ')
    results.push(item)
}
```

and then change the template to use `.suggestion` instead of `.tekst`

Hope you will fix it!

**Comment by rasmus0201** [comment]
Note: the suggestion code i made doesn't support for multiline

**Comment by AncaIO** [comment]
Hi @rasmus0201, sorry for the late reply - been away from Vue / JS projects for a while... Will look into it and make the necessary changes. Thanks for posting the issue.

**Comment by rasmus0201** [comment]
@AncaIO Thanks! :)
