### ISSUE TITLE
Unable to use package due to CORS issue.

### ISSUE THREAD

**Issue by david00910** [AncaIO/vue-dawa#14]
Dear Anca,

Thank you for this awesome package for Vue. I am building a real estate webapp here in Denmark, which I would like to use some BBR data from DAWA for. My problem is that the autocomplete does not work because of CORS issues. This is something that is out of my hands, as the header with the correct Cross-Site-Reference options must be set by the provider of the API. That part is understandable. 

However, your Demo still works and I do not understand how. Could you please take a look into that? 

This is the error I am getting when I try to start typing an address:

"Access to XMLHttpRequest at 'http://dawa.aws.dk/autocomplete?q=aaa&type=adresse&caretpos=3&supplerendebynavn=true&stormodtagerpostnumre=true&multilinje=true&fuzzy=' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response."

Thank you!

**Comment by AncaIO** [comment]
Hi @david00910,

Sorry for the late reply - been away from Vue/JS world for a while. I will look into this ASAP. Thank you for using vue-dawa and posting the issue.

**Comment by david00910** [comment]
Hi Anca,

Since then, the guys behind the official API solved it. So the issue was
not with your package. :)

Anca <notifications@github.com> ezt írta (időpont: 2020. márc. 30., H
21:20):

**Comment by AncaIO** [comment]
Perfect! Closing this.
