### ISSUE TITLE
When searching for the first time, the list autoselects when it is down to one option

### ISSUE THREAD

**Issue by Nnoerregaard** [AncaIO/vue-dawa#18]
This disrupts the user flow when a street number is also needed. The current behaviour can be seen here https://gyazo.com/3afeee4691b5fbd2c28cba42f8a5add0

This only occurs the first time around. Subsequent searches behave as expected. The expected behaviour can be seen here https://gyazo.com/9c204699f7c7af41271513aeb7bd583e

The expected behaviour should always occur as the undesired behaviour is very disruptive to the user. I've identified the issue and created a PR which should fix it: https://github.com/AncaIO/vue-dawa/pull/17

**Comment by AncaIO** [comment]
@Nnoerregaard Thanks for the fix. It's included in v2.0.10 (available on npm as of today).
