### ISSUE TITLE
Unable to click on selected address

### ISSUE THREAD

**Issue by jycr753** [AncaIO/vue-dawa#2]
There is no way to select an address by clicking it

![2018-04-06 14 53 53](https://user-images.githubusercontent.com/1929689/41770602-0a0902ea-7613-11e8-97fe-3d318f81d957.gif)

**Comment by AncaIO** [comment]
Hi,

Thanks for reporting this. I am, however, not able to replicate this. Are you using the latest version (1.1.2)?

**Comment by AncaIO** [comment]
Update to version 1.1.4 by running `npm update vue-dawa` in your project and try again. 

If it's still an issue, let me know.

**Comment by jycr753** [comment]
@AncaIO Thanks so much I will try it asap :)

**Comment by segadora** [comment]
I was expiriencing the same issue. This was due to `tabindex="-1"` on a modal-mask from bootstrap.

```    <div
      class="modal-mask"
      tabindex="-1"
      role="dialog"
      aria-hidden="false"
    >
```

Removing tabindex solved the issue
