### ISSUE TITLE
Error when used in local environment

### ISSUE THREAD

**Issue by TheGuldberg** [AncaIO/vue-dawa#5]
### Error
![image](https://user-images.githubusercontent.com/32705674/49380946-27dc7a00-f713-11e8-9a77-73cb9e9463e3.png)

### Version
1.1.4

### Steps to reproduce
In local environment
1. Create vue application
2. Download package
3. Setup vue-dawa with application

### Additional information
Code which is making the bug:
`range = document.selection.createRange()` in `utils.js`

`document.selection` is undefined, but can be solved with `document.getSelection` which returns the correct selection. However this will not solve it, as the method `createRange()` does not exist as a function.

**Comment by AncaIO** [comment]
Hi @TheGuldberg ,

I have tried to replicate this issue as per your instructions, and I was unable to re-create the bug. 

What browser were you using? 

Also, can you give me some information about your dev setup?

**Comment by TheGuldberg** [comment]
@AncaIO 

I found the culprit, and it was a mistake of our own. The vue-dawa component catched another id, which referenced an html form. That is why it couldn't get the range of the element. I hope i didn't disturb you too much.

**Comment by AncaIO** [comment]
@TheGuldberg no problem :) glad you found the problem and things are working as intended.
